version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: spotify_redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: spotify_redpanda_console
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKERS=redpanda:29092
    ports:
      - "8080:8080"

volumes:
  redpanda_data:
